# fly.toml app configuration file generated for kevincasey on 2023-04-28T17:58:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kevincasey"
primary_region = "lax"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
